const semesters = {
  1: [
    { code: "EE-PC101", name: "Electrical Engineering Material", credits: 3 },
    { code: "EE-PC102", name: "Basic Electronics", credits: 4 },
    { code: "FC-011", name: "Applied Mathematics-1", credits: 4 },
    { code: "FC-021", name: "Basic Engineering Graphics", credits: 3 },
    { code: "FC-031", name: "Basic Engineering Workshop Technology", credits: 3 },
    { code: "FW-DP031", name: "Face the World Skills-1 (SEL)", credits: 1 },
    { code: "HS-021", name: "English Communication-1", credits: 1 },
    { code: "HS-051", name: "Sports & Yoga", credits: 0 },
  ],
  2: [
    { code: "EE-FC203", name: "Elements of Mechanical Engineering", credits: 3 },
    { code: "EE-PC201", name: "Electrical Workshop-1", credits: 3 },
    { code: "EE-PC202", name: "Electrical Engineering Drawing", credits: 3 },
    { code: "EE-51201", name: "Industry Visit/Field Visit/Seminar", credits: 1 },
    { code: "FC-012", name: "Applied Mathematics-II", credits: 4 },
    { code: "FC-CH051", name: "Basic Sciences (Applied Chemistry)", credits: 2.5 },
    { code: "FC-PH051", name: "Basic Sciences (Applied Physics)", credits: 2.5 },
    { code: "FW-DP032", name: "Face the World Skills (Socio-Emotional Learning)", credits: 1 },
    { code: "FW-DP072", name: "Face the World Skills (Financial Literacy)", credits: 1 },
    { code: "HS-022", name: "English Communication-II", credits: 1 },
  ],
  3: [
    { code: "HS-023", name: "English Communication-III", credits: 1 },
    { code: "HS-011", name: "Evs", credits: 1},
    { code: "EE-PC302", name: "Electrical Machine-I", credits: 5 },
    { code: "EE-PC301", name: "Electrical & Electronic Measurement", credits: 5 },
    { code: "EE-PC304", name: "Electric Workshop-II", credits: 3 },
    { code: "FW-DP033", name: "Face the World Skills-III (SEL)", credits: 1 },
    { code: "FW-DP033", name: "Face the World Skills-III (Design Thinking)", credits: 1 },
    { code: "EE-PC303", name: "Electric Circuit", credits: 5 },
  ],
  4: [
    { code: "EE-PC401", name: "Electrical Machines-II", credits: 4 },
    { code: "EE-PC402", name: "Electric Power Generation, Transmission and Distribution", credits: 4 },
    { code: "EE-PC403", name: "Control System", credits: 4 },
    { code: "EE-PE401", name: "Power Electronics and Drives", credits: 4 },
    { code: "EE-PE403", name: "Electric Traction", credits: 4 },
    { code: "FW-DP064", name: "Face The World Skills-IV (Entrepreneurship)", credits: 1 },
    { code: "HS-024", name: "English Communication-IV", credits: 1 },
  ],
  5: [
    {code : "EE-PC501",name: "Non-Conventional Energy Sources",credits:5},
    {code :"EE-PC502", name: "Digital Electronics and Microprocessor",credits:5},
    {code :"EE-PC504", name: "Basics of Electronics Communication",credits:3},
    {code :"EE-PE503", name: "Elective",credits:3},
    {code :"EE-SI501", name: "Summer Training",credits:3},
    {code :"HS-035", name: "English for Success",credits:1},
  ]
};
